"""
backend/main.py
────────────────
FastAPI application entry point.

Registers all routers, sets up CORS, and loads the RAG pipeline
on startup using FastAPI's lifespan context manager.

HOW TO RUN:
    uvicorn backend.main:app --reload --port 8000

API DOCS (auto-generated by FastAPI):
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc UI
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.api.routes import health, ingest, query, documents
from backend.core.rag_pipeline import rag_pipeline
from backend.core.config import CORS_ORIGINS, VECTORSTORE_DIR


# ── Lifespan: runs at startup and shutdown ───────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Startup: try to load an existing vector store.
    If none exists yet, the pipeline stays in 'not ready' state until
    the user ingests documents via POST /api/ingest.
    """
    print("🚀 EduRAG Backend starting up...")
    loaded = rag_pipeline.load(VECTORSTORE_DIR)
    if loaded:
        stats = rag_pipeline.get_stats()
        print(f"✅ Knowledge base loaded — {stats['total_chunks']} chunks indexed.")
    else:
        print("ℹ️  No knowledge base found. Ingest documents to get started.")

    yield  # ← app runs here

    print("🛑 EduRAG Backend shutting down.")


# ── FastAPI App ──────────────────────────────────────────────────────────────
app = FastAPI(
    title="EduRAG API",
    description=(
        "Retrieval-Augmented Generation backend for Educational Systems.\n\n"
        "**Endpoints:**\n"
        "- `GET  /api/health`               — service health check\n"
        "- `POST /api/ingest`               — upload & index documents\n"
        "- `POST /api/ingest/reload`        — reload from existing vector store\n"
        "- `DELETE /api/ingest/clear`       — clear all indexed data\n"
        "- `POST /api/query`                — ask a question (RAG pipeline)\n"
        "- `GET  /api/documents`            — list indexed documents\n"
        "- `DELETE /api/documents/{name}`   — remove a specific document\n"
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# ── CORS ─────────────────────────────────────────────────────────────────────
# Allows the Streamlit frontend (localhost:8501) to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Route Registration ────────────────────────────────────────────────────────
# All routes are prefixed with /api for clean separation.
app.include_router(health.router,    prefix="/api", tags=["Health"])
app.include_router(ingest.router,    prefix="/api", tags=["Ingestion"])
app.include_router(query.router,     prefix="/api", tags=["Query"])
app.include_router(documents.router, prefix="/api", tags=["Documents"])


@app.get("/", include_in_schema=False)
def root():
    return {
        "message": "EduRAG API is running.",
        "docs": "/docs",
        "health": "/api/health",
    }
